/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jethro
 */
public class MedianFilterUI extends javax.swing.JFrame {
    static String input;
    static int filterWindow=3;
    static int size;
    static String output;

    /**
     * Creates new form MedianFilterUI
     */
    public MedianFilterUI() {
        initComponents();
        jSliderFilter.setValue(filterWindow);
        jSpinnerFilter.setValue(filterWindow);
        jSpinnerArray.setValue(1000);
//        jSliderArray.setValue(size/1000);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelBackground = new javax.swing.JPanel();
        jLabelTime = new javax.swing.JLabel();
        jLabelHeading = new javax.swing.JLabel();
        jLabelSerial = new javax.swing.JLabel();
        jLabelParallel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSerial = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPar = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDelta = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSerial = new javax.swing.JTextField();
        jTextFieldPar = new javax.swing.JTextField();
        jTextFieldDelta = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIndex = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSliderThreshhold = new javax.swing.JSlider();
        jSliderFilter = new javax.swing.JSlider();
        jSliderArray = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerThresh = new javax.swing.JSpinner();
        jSpinnerArray = new javax.swing.JSpinner();
        jSpinnerFilter = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSpeedE = new javax.swing.JTextField();
        jTextFieldSpeedO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldSpeedOfastest = new javax.swing.JTextField();
        jPanelParameters = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTime.setText("Time taken (ms)");

        jLabelHeading.setText("Median Filter");

        jLabelSerial.setText("Serial");

        jLabelParallel.setText("Parallel");

        jScrollPane1.setViewportView(jListSerial);

        jScrollPane2.setViewportView(jListPar);

        jLabel4.setText("Delta");

        jScrollPane3.setViewportView(jListDelta);

        jLabel5.setText("Mean");

        jListIndex.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListIndex);

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Parameters");

        jLabel7.setText("Sequential Threshhold");

        jSliderThreshhold.setMajorTickSpacing(500);
        jSliderThreshhold.setMaximum(5000);
        jSliderThreshhold.setMinimum(500);
        jSliderThreshhold.setMinorTickSpacing(50);
        jSliderThreshhold.setPaintLabels(true);
        jSliderThreshhold.setPaintTicks(true);
        jSliderThreshhold.setSnapToTicks(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSpinnerThresh, org.jdesktop.beansbinding.ELProperty.create("${value}"), jSliderThreshhold, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jSliderFilter.setMajorTickSpacing(10);
        jSliderFilter.setMaximum(23);
        jSliderFilter.setMinimum(3);
        jSliderFilter.setMinorTickSpacing(1);
        jSliderFilter.setPaintLabels(true);
        jSliderFilter.setPaintTicks(true);
        jSliderFilter.setSnapToTicks(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSpinnerFilter, org.jdesktop.beansbinding.ELProperty.create("${value}"), jSliderFilter, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jSliderFilter.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jSliderFilterCaretPositionChanged(evt);
            }
        });
        jSliderFilter.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSliderFilterPropertyChange(evt);
            }
        });

        jSliderArray.setMajorTickSpacing(100);
        jSliderArray.setMaximum(1000);
        jSliderArray.setMinorTickSpacing(10);
        jSliderArray.setPaintLabels(true);
        jSliderArray.setPaintTicks(true);
        jSliderArray.setSnapToTicks(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSpinnerArray, org.jdesktop.beansbinding.ELProperty.create("${value}"), jSliderArray, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel8.setText("Elements in array (1000s)");

        jLabel9.setText("Filter window");

        jSpinnerThresh.setModel(new javax.swing.SpinnerNumberModel(1000, 500, 5000, 500));

        jSpinnerArray.setModel(new javax.swing.SpinnerNumberModel(3, 3, 10000, 1));
        jSpinnerArray.setValue(jSpinnerArray.getValue());

        jSpinnerFilter.setModel(new javax.swing.SpinnerNumberModel(3, 3, 23, 1));
        jSpinnerFilter.setValue(jSliderFilter.getValue());
        jSpinnerFilter.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jSpinnerFilterCaretPositionChanged(evt);
            }
        });
        jSpinnerFilter.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinnerFilterPropertyChange(evt);
            }
        });

        jLabel1.setText("Speedup");

        jLabel2.setText("Expected");

        jLabel3.setText("Observed");

        jLabel10.setText("Observed (Fastest)");

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(13, 13, 13)
                                .addComponent(jTextFieldSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(67, 67, 67))
                                    .addComponent(jTextFieldSpeedO)
                                    .addComponent(jTextFieldSpeedE, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelParallel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jLabelTime))
                        .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSerial)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSpeedOfastest, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(jSliderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel7))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jLabel6))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(jSliderArray, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelHeading)
                                        .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                            .addComponent(jSliderThreshhold, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSpinnerThresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(36, 36, 36))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(380, 380, 380))))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeading)
                .addGap(36, 36, 36)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderThreshhold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerThresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSliderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jSpinnerFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSerial)
                            .addComponent(jLabelParallel)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSpeedE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSpeedO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldSpeedOfastest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))))
        );

        javax.swing.GroupLayout jPanelParametersLayout = new javax.swing.GroupLayout(jPanelParameters);
        jPanelParameters.setLayout(jPanelParametersLayout);
        jPanelParametersLayout.setHorizontalGroup(
            jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelParametersLayout.setVerticalGroup(
            jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerFilterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerFilterPropertyChange
        // TODO add your handling code here:
        jSliderFilter.setValue((int)jSpinnerFilter.getValue());
    }//GEN-LAST:event_jSpinnerFilterPropertyChange

    private void jSpinnerFilterCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSpinnerFilterCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerFilterCaretPositionChanged

    private void jSliderFilterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSliderFilterPropertyChange
        // TODO add your handling code here:
        jSpinnerFilter.setValue((int)jSliderFilter.getValue());
    }//GEN-LAST:event_jSliderFilterPropertyChange

    private void jSliderFilterCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSliderFilterCaretPositionChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jSliderFilterCaretPositionChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int seq_thresh = jSliderThreshhold.getValue();
        filterWindow = jSliderFilter.getValue();
                int arrSize = jSliderArray.getValue()*1000;

        Controller obj = new Controller();
//        obj.setOutputFile(output);
obj.setFilterWindow(filterWindow);
        obj.setSeqThresh(seq_thresh);
        try {
            obj.setInput(input,arrSize);
        } catch (IOException ex) {
            Logger.getLogger(MedianFilterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println(filterWindow);
            float [] seq = null;
        try {
            System.out.println(obj.outputFile);
            seq = obj.getSerialTimes();
        } catch (IOException ex) {
            Logger.getLogger(MedianFilterUI.class.getName()).log(Level.SEVERE, null, ex);
        }

            float [] par = null;
        try {
            par = obj.getParTimes();
        } catch (IOException ex) {
            Logger.getLogger(MedianFilterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            float [] delta = obj.getDelta(par, seq);
            float mean_s =0; float mean_p=0;float  mean_d=0;
            for (int i = 1; i < delta.length; i++) {
                mean_s += seq[i];
                mean_p += par[i];
                mean_d += Math.abs(delta[i]);

            }
            mean_s /=delta.length-1; mean_p/=delta.length-1;mean_d/=delta.length-1;

            jListPar.setListData(obj.toStringArr(par));
            jListSerial.setListData(obj.toStringArr(seq));
            jListDelta.setListData(obj.toStringArr(delta));
            jTextFieldDelta.setText(String.format("%.3f",mean_d));
            jTextFieldPar.setText(String.format("%.3f",mean_p));
            jTextFieldSerial.setText(String.format("%.3f",mean_s));
            float  min_s = getMin(seq);
            float  min_p = getMin(par);
            jTextFieldSpeedOfastest.setText(String.format("%.3f",min_s/min_p));
            jTextFieldSpeedO.setText(String.format("%.3f",mean_s/mean_p));
            //            double proportionSerial = jSliderThreshhold.getValue()/jSliderArray.getValue()*1000;
            //            jTextFieldSpeedE.setText(String.format("%s",1/(proportionSerial+(1-proportionSerial)/Runtime.getRuntime().availableProcessors())));
            System.out.println(Arrays.equals(Controller.serArr,Controller.parArr));
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public float  getMin(float  [] a){
        float  min = a[0];
        for (int i = 1; i < a.length; i++) {
            float  d = a[i];
            if (d<min)min = d;
            
        }
        return min;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println(args.length);
        if(args.length==3){
            
        input = args[0];
        filterWindow = Integer.parseInt(args[1]);
        output = args[2];
        int seq_thresh = 1000;
                int arrSize = 1000000;

        Controller obj = new Controller();
            System.out.println(output);
        obj.setOutputFile(output);
obj.setFilterWindow(filterWindow);
        obj.setSeqThresh(seq_thresh);
        try {
            obj.setInput(input,arrSize);
        } catch (IOException ex) {
            Logger.getLogger(MedianFilterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            float [] seq = null;
        try {
            seq = obj.getSerialTimes();
        } catch (IOException ex) {
            Logger.getLogger(MedianFilterUI.class.getName()).log(Level.SEVERE, null, ex);
        }

            float [] par = null;
        try {
            par = obj.getParTimes();
        } catch (IOException ex) {
            Logger.getLogger(MedianFilterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        } else{
            input = "sampleinputfile.txt";
//        size = Integer.parseInt(args[2]);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedianFilterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedianFilterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedianFilterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedianFilterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedianFilterUI().setVisible(true);
            }
        });
    }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelParallel;
    private javax.swing.JLabel jLabelSerial;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JList<String> jListDelta;
    private javax.swing.JList<String> jListIndex;
    private javax.swing.JList<String> jListPar;
    private javax.swing.JList<String> jListSerial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelParameters;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSliderArray;
    private javax.swing.JSlider jSliderFilter;
    private javax.swing.JSlider jSliderThreshhold;
    private javax.swing.JSpinner jSpinnerArray;
    private javax.swing.JSpinner jSpinnerFilter;
    private javax.swing.JSpinner jSpinnerThresh;
    private javax.swing.JTextField jTextFieldDelta;
    private javax.swing.JTextField jTextFieldPar;
    private javax.swing.JTextField jTextFieldSerial;
    private javax.swing.JTextField jTextFieldSpeedE;
    private javax.swing.JTextField jTextFieldSpeedO;
    private javax.swing.JTextField jTextFieldSpeedOfastest;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
